### ISSUE TITLE
missing language strings

### ISSUE THREAD

**Issue by iv-enovation** [KQMATH/moodle-mod_jazzquiz#1]
When in full development mode, there are some notifications of the missing language strings in different places. For example:
(starting a new session)
- Warning: array_merge() expects at least 1 parameter, 0 given in /var/www/ticket/moodle341/question/engine/datalib.php on line 103
- String does not exist. Please check your string definition for responded/jazzquiz
- Invalid get_string() identifier: 'responded' or component 'jazzquiz'. Perhaps you are missing $string['responded'] = ''; in mod/jazzquiz/lang/en/jazzquiz.php?

(editing a question)
- Invalid get_string() identifier: 'notime' or component 'jazzquiz'. Perhaps you are missing $string['notime'] = ''; in mod/jazzquiz/lang/en/jazzquiz.php?
- Help title string does not exist: [questiontime, jazzquiz]
- Invalid get_string() identifier: 'questiontime' or component 'jazzquiz'. Perhaps you are missing $string['questiontime'] = ''; in mod/jazzquiz/lang/en/jazzquiz.php?

**Comment by rgbenergy** [comment]
Fixed the strings.
