### ISSUE TITLE
Bug:  Better error message when no quiz is running

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#101]
Guest students joining the activity when the quiz is not in sTjeession receives a red error message: Sorry, but you do not currently have permissions to do that (Attempt a JazzQuiz).

The error message should say that there is no running session, suggesting that the student waits for the teacher to start it, rather than suggesting a permission problem.

This should be tested to see if logged in students see the same error.

**Comment by jorgenfinsveen** [comment]
Bug resolved and tested in branch bug/#101. Is not merged into main branch yet
