### ISSUE TITLE
Changing save answer button text from "save" to "submit"

### ISSUE THREAD

**Issue by jorgenfinsveen** [KQMATH/moodle-mod_jazzquiz#117]
A suggestion:

<img width="497" alt="Skjermbilde 2023-08-01 kl  10 01 28" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/18f2438e-b04f-4ced-8f95-adb9071248a3">

Should we change the button text from "Save" to "Submit"? 

When clicking the button, the answer is submitted and the student is no longer able to change the answer. Personally I feel that "Save" can be a little misleading. I can imagine that a user would think that one can save the answer, change it, and resave it, until the question countdown reaches 0. @hgeorgsch what do you think?

**Comment by jorgenfinsveen** [comment]
Made a new branch and implemented this in order to see how the implementation of suggestion would turn out. 

New layout:

<img width="410" alt="Skjermbilde 2023-08-01 kl  10 33 25" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/09e769f6-2d65-4e14-932d-9107bd54f1ee">


Another idea is to add some help text which informs that submitting/saving cannot be undone.

Creates a pull request for the suggested adjustment. If the adjustment is favorable the request could be accepted, or rejected if otherwise.

**Comment by hgeorgsch** [comment]
I agree with you @jorgenfinsveen .  Submit is better than save.
