### ISSUE TITLE
'Start quiz' button

### ISSUE THREAD

**Issue by kkleba16** [KQMATH/moodle-mod_jazzquiz#124]
It can be a bit confusing at first that 'Start quiz' is not simply a title but actually a button, so it would be nice with some visual indication(s) that it in fact is a button, e.g., a simple border around the text.

![Moodle 4 1 Start Quiz](https://github.com/KQMATH/moodle-mod_jazzquiz/assets/27851362/61196448-b1c7-4bc2-bc62-18811d445d03)

**Comment by i11info** [comment]
Put this custom SCSS in your active moodle theme:

#jazzquiz_controls .btn {
  border: solid;
  border-radius: 1rem;
}

**Comment by sebastsg** [comment]
Will be fixed as part of release 1.3. From now on we will now try to use the theme style more.
