### ISSUE TITLE
Categorise IMPROV questions

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#15]
All IMPROV questions should be placed in a dedicated category for JazzQuiz. Is it possible to create them System level? Having them course or activity level is not a big deal if they get a category directly under the top level (sibling of default).

**Comment by sebastsg** [comment]
Now using the default category for the activity. This bug actually is breaking improvised questions, and I'm surprised nobody (including myself) has complained about it.
