### ISSUE TITLE
JazzQuiz breaks javascript in Moodle 3.5.1 when using Internet Explorer

### ISSUE THREAD

**Issue by rolandsherwood2** [KQMATH/moodle-mod_jazzquiz#16]
Hello Sebastian. I just wanted to let you know that we are currently in the process of upgrading to Moodle 3.5.1 and have discovered what appears to be a major issue with using version 2018062612 of JazzQuiz and Internet Explorer 11. Basically, installing JazzQuiz under a freshly installed version of 3.5.1 (with no other plugins installed) results in a a javascript error/conflict which breaks the majority of javascript in Moodle site-wide - meaning things like Boost's menus don't function correctly, etc. Internet Explorer's console reports the error as 'No define call for core/first (http://requirejs.org/docs/errors.html#nodefine)'. I'm not sure exactly what this means, but I've conducted several tests and was able to reproduce this issue each time. What's strange is that the error doesn't appear to affect other browsers such as Chrome, Safari, Firefox - only IE. Nevertheless, since IE is still very widely used, I just thought it worth reporting in case other JazzQuiz users are affected also. Thanks again for sharing this wonderful plugin, and for any support you can provide re. this issue.

**Comment by hgeorgsch** [comment]
Thanks for letting us know. It is likely to hit me heavy when I meet the students on Friday ...
It seems that the link you quote points very specifically to plausible causes, so I trust we can find the bug.

**Comment by sebastsg** [comment]
Seems like Internet Explorer doesn't support modern JavaScript syntax. I will look into using Babel to convert into IE-compatible JavaScript.

**Comment by sebastsg** [comment]
Fixed in master. Will publish new version later this week.

Notes regarding fix: Added .babelrc and build.sh to amd folder. The build script will first run Babel, then run grunt amd tasks afterwards. Should probably be done as a grunt task later on.
