### ISSUE TITLE
Metadata fills up question display

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#17]
When a question is displayed, the metadata takes up a lot of space. Questions with a lot of text becomes difficult to read in a narrow box in the middle.

Is it possible to display the timer and the number of responses under the question number on the left hand side?  Did we discuss this earlier?

**Comment by sebastsg** [comment]
The question will now take up 100% of the width, and the timer etc is moved to below the controls. This does not waste that much vertical space, and it looks a bit better as well I think. The bar graph also gets more space.
