### ISSUE TITLE
Duplicate IMPROV questions

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#21]
Several copies of the same IMPROV question now appears in the quiz. I have not tested on a fresh installation, so it is possible that the problem only occurs with an upgrade. If possible, we should avoid it nevertheless.

**Comment by hgeorgsch** [comment]
The duplication only appears in the drop down menu during a quiz session. No duplicate questions can be found in the question bank views.

**Comment by hgeorgsch** [comment]
Conjecture. The activity drop-down menu displays all IMPROV questions from every JazzQuiz instance in the course/on the site.

**Comment by sebastsg** [comment]
Fixed. Category was not checked in query.
