### ISSUE TITLE
Custom IMPROV questions do not display

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#24]
Even if a question is added to the JazzQuiz category, with the {IMPROV} prefix, it is not included in the drop-down menu.

**Comment by sebastsg** [comment]
I have tested this, and it works fine for me. Are you sure {IMPROV} has no accidental space before?

**Comment by hgeorgsch** [comment]
OK. No idea what was wrong, but now it seems to work.
