### ISSUE TITLE
error messages in report

### ISSUE THREAD

**Issue by iv-enovation** [KQMATH/moodle-mod_jazzquiz#3]
in a report document i generated, i received following:

Student,True / False (truefalse),Short answer (shortanswer),3 Multichoice Options (multichoice),^M
cali the kot,<br />
<b>Notice</b>:  Only variables should be passed by reference in <b>/var/www/ticket/moodle341/mod/jazzquiz/classes/report_overview.php</b> on line <b>81</b><br />
False,<br />
<b>Notice</b>:  Only variables should be passed by reference in <b>/var/www/ticket/moodle341/mod/jazzquiz/classes/report_overview.php</b> on line <b>81</b><br />
what?,<br />
<b>Notice</b>:  Only variables should be passed by reference in <b>/var/www/ticket/moodle341/mod/jazzquiz/classes/report_overview.php</b> on line <b>81</b><br />
C,

**Comment by rgbenergy** [comment]
reset() was given a return value as param, fixed by making temporary variable
