### ISSUE TITLE
No MathJax in responses

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#34]
ShortMath now seems to work, but the response listing shows unrendered LaTeX.

**Comment by hgeorgsch** [comment]
This works with one logged in student user and firefox @windows (VDI), edge @windows (VDI) and firefox @debian. 
It still does not appear to work with a class in Fogdegården, using chrome or edge  @windows. This may be due to class size or obscure software versions.

**Comment by hgeorgsch** [comment]
It halfway works in a class with firefox @ debian.  However, automatic page refreshes can break the MathJax rendering.  Manual refresh can solve the problem in some instances.
Probably good enough to use for a skilled user, but hard on casual users. Further investigation is necessary.

**Comment by sebastsg** [comment]
I think I found the culprit. MathJax didn't like that I notified it with one wrapper per response to render. It's now changed to use the response list itself. I did some testing with adding 100+ rather big testing responses, and this definitely sped it up by 2-3 times.
