### ISSUE TITLE
Configurable anonymity

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#35]
Having to implement GDPR support, it is worth thinking about anonymity. Is it possible to make configurable anonymity, as ActiveQuiz is reported to support?

**Comment by sebastsg** [comment]
Added. Two modes: 
- Anonymous answers, but attendance is visible. 
- Fully anonymous, and no user data is saved

The data is only anonymized after the instructor ends a session, but that should be fine. At least for now.
