### ISSUE TITLE
Bug with Moodle 3.1.6

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#37]
Quoted from moodle plugin directory:
Hi Sebastian, please help me. I installed the JazzQuiz mod in moodle 3.1.6, but when I try tab edit nothing appears. I enabled the depuration mode and get this error message: Fatal error: Call to undefined method mod_jazzquiz\bank\jazzquiz_question_bank_view::display_question_bank_header() in /var/www/html/profesional/mod/jazzquiz/classes/bank/jazzquiz_question_bank_view.php on line 88

**Comment by sebastsg** [comment]
Turns out this is an issue with 3.4 and earlier as well. It's been fixed in develop branch, and will be part of the next release.
