### ISSUE TITLE
Delete question breaks quiz

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#40]
It is possible for the user to delete a question from the database, without removing it from existing jazzquiz instances. The result is that the jazzquiz activity no longer works, cannot be entered, and cannot be repaired.

**Comment by hgeorgsch** [comment]
Some doubt was raised about this issue.  There should be checks to prevent the error. It would be useful to replicate the bug. Please report.
If the bug can be replicated, we need to handle the missing question as an exception in JazzQuiz, as we cannot change the question bank in moodle core.  Please identify relevant places to detect the exception, as a first step before changing the code.

**Comment by sebastsg** [comment]
There was indeed a problem. Questions are now deleted in the JazzQuiz also when a missing Moodle question is detected.
