### ISSUE TITLE
MathJax does not always render

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#43]
It happens relatively often, both in the teacher and the student interface, that MathJax does not render on first attempt. A page reload usually resolves this, bit this is not ideal since input and settings would then be lost.

**Comment by sebastsg** [comment]
The question is now wrapped with a tag with the same class as responses, and that seems to have fixed it. Also emitting the event when the question form loads, in addition to new responses coming in.
