### ISSUE TITLE
default questions cannot be deleted

### ISSUE THREAD

**Issue by iv-enovation** [KQMATH/moodle-mod_jazzquiz#6]
default questions can be listed in "Default for System" question bank, but when attempted to delete they stay. An error message is shown for a moment until replaced by Ajax

**Comment by rgbenergy** [comment]
A new config section for enabled default questions has been added. Questions are added/removed depending on that. Also, if a question is removed from the question bank, the config will be updated. Config updates and add/remove question code is run when accessing view.php

It is best to reinstall the plugin, or else the config might not be synced correctly with the qbank.
