### ISSUE TITLE
User Story: Random Questions

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#68]
One user has requested random questions.  I am not sure if this is worth providing for, but it is worth seeing how difficult it would be.

   Here is one scenario:

   You have a few minutes left to the end of the session with everything done
   and dusted. You ask your students, "Would you like to have a short fun
   quiz?" They never fails to say yes, obviously. You run your say 3-question
   quiz , with say 2 questions drawn at random from a "riddle/puzzle/trivia"
   category and one question drawn from a "serious learning" category, and
   the students will try to crack the quiz. Voilà, you've just had a fun and
   useful round-off to your session.

   Here is another:

   A weekly quiz, from Monday to Friday, one question per day, again with a
   mix of fun and serious questions, during which all are welcome to
   participate, with a sum-up posted every Saturday. The question time could
   be anywhere between 1 hour and 24 h, so say I run each question at 8 am
   and it will be open for 1 hour, or it will remain open until the next day.

   And while we are at it, I do appreciate the usefulness and practicality of
   the "use case" approach. It pays to have focus. However, it also pays not
   to limit ourselves within the constraints of the initial use case we
   started with. So, if it doesn't take a lot of work to add a certain
   functionality, I find it quite reasonable to do so. This will allow users
   to come up with new and extended "use cases" we didn't think of in the
   first place. In other words, I see "use case" as a starting point to focus
   and shape our efforts, not as a rigid boundary. The former is necessary;
   the latter robs us of the potential to grow, expand, and evolve. I hope
   you agree.

   If it's not practical to add the random question feature, I perfectly
   understand. If it is, please consider doing it. :-)

**Comment by hgeorgsch** [comment]
Note, this has been out of scope, leaving it for the original ActiveQuiz activity.  Now, ActiveQuiz has not been maintained since Moodle 3.2 ...

**Comment by sebastsg** [comment]
I'll take a look this evening.
