### ISSUE TITLE
undefined property in jazzquiz_disabled_condition.php

### ISSUE THREAD

**Issue by iv-enovation** [KQMATH/moodle-mod_jazzquiz#7]
when editing a quiz (after fresh plugin install with no pre-existing questions) got 2 notices:
Notice: Undefined property: stdClass::$enabledqtypes in /var/www/ticket/moodle341/mod/jazzquiz/classes/bank/jazzquiz_disabled_condition.php on line 56
Notice: Undefined property: stdClass::$enabledqtypes in /var/www/ticket/moodle341/mod/jazzquiz/classes/bank/jazzquiz_question_bank_view.php on line 156

then, when "Create new question", unable to click "Add" as entries on the left column are not selectable

**Comment by rgbenergy** [comment]
I should have noticed that, my bad. Fixed the string in all places.
