### ISSUE TITLE
"add to quiz" button does not work

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#72]
This is copied from #70. Quoting @pejhab
«The "add to quiz" button does not work for me. I select some questions (from a category) and then click on "add to quiz" but nothing happens.»

I was not able to reproduce the bug, but it should be investigated.

**Comment by pejhab** [comment]
I have a screen capture but it is 40 MB... :-(

**Comment by pejhab** [comment]
I have set up a Moodle course and an account for you to try this out on my website. How can I send you the access details?

**Comment by hgeorgsch** [comment]
Thanks.  You can send to georg+github@schaathun.net

**Comment by hgeorgsch** [comment]
Now I was able to reproduce the bug on my own system, following an upgrade of Moodle (3.9.6 as of 20210420).  It produces no error, not even with full DEVELOPER mode.

**Comment by hgeorgsch** [comment]
This is a javascript error.  It triggers an «Uncaught undefined» error in first.js:422

**Comment by hgeorgsch** [comment]
It is a little bit odd that the Add to quiz-button shows also when an empty list of questions is shown.  Delete and Move to are hidden in this case.

**Comment by hgeorgsch** [comment]
I have tested JazzQuiz master branch with Moodle 3.10.3 (20210427), and the add to quiz button works here.
It does not work with the develop branch on the same Moodle version.
@sebastsg do you have any idea what could have broken this?

**Comment by pejhab** [comment]
Hello, 
Have there been any progress with this issue?
Have a good day!

**Comment by julianmontague** [comment]
I can confirm that I was able to reproduce this on Moodle 4.0 @hgeorgsch. Working on debugging now.
