### ISSUE TITLE
Include student ID in session and attendance reports

### ISSUE THREAD

**Issue by altugozcelikkale** [KQMATH/moodle-mod_jazzquiz#76]
Thank you for this great plugin. Is there a way more columns such as student ID can be included in the csv reports? That will help sort out discrepancies associated with students having the exact same name (which is not common but still happens).

**Comment by LeonOfTheNap** [comment]
Hi,
I've just made a pull request and if accepted, should make it so that the moodle id number of a student is displayed on the final report.

Just a heads-up, that will require your university to have the optional ID number set in moodle for every student. 
![image](https://user-images.githubusercontent.com/95309331/210121101-90b5231d-d0de-4a49-99bf-c80a04cb4876.png)

**Comment by jorgenfinsveen** [comment]
This implementation seems to be in order. ID number appears in csv reports

**Comment by jorgenfinsveen** [comment]
This may be an unrelated issue...

<img width="310" alt="Skjermbilde 2023-06-26 kl  08 52 50" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/a7cae9f7-9e0f-47f7-bce7-907e55962ba4">



<br/><br/>When clicking on the button _Download report_, I receive a file named _session_1_sess_attendance.csv_.

<img width="365" alt="Skjermbilde 2023-06-26 kl  09 00 51" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/f9403ae2-8987-4499-aa0d-4af5eacb602b">

<br/>This seems to be in order. However, when clicking on the button _Download report_, I receive a file named _session_1_sess.csv_. The contents of the file does not seem to give any meaningful information beyond listing the name of the questions in the quiz:

<img width="925" alt="Skjermbilde 2023-06-26 kl  09 12 57" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/a37d67db-aaec-49b3-a25c-38a33ee8fa3f">

Is it supposed to be like this, or should this be looked into?

**Comment by jorgenfinsveen** [comment]
Tested with 4 different student accounts using Google Chrome and Mozilla Firefox in both with and without incognito-mode. All answers were registered and each student ID was correct.



<br/><br/>Session report:

<img width="663" alt="Skjermbilde 2023-06-26 kl  11 50 54" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/a9470934-95f7-4ae9-a7ba-e7b9c741c6dd">



<br/><br/>Attendance list:

<img width="263" alt="Skjermbilde 2023-06-26 kl  11 52 18" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/fafa7def-76a8-4b3f-8757-f0fb8c8b592d">

The only issue here is that the column __First Name__ actually contains the users last name and vice versa. I will try to resolve this before closing the issue.

**Comment by jorgenfinsveen** [comment]
@hgeorgsch I have tested this now. It seems to be in order.

<br/>Fully anonymous session:

<img width="261" alt="Skjermbilde 2023-06-26 kl  12 08 24" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/12cc7513-bd39-4017-9c64-4386a958b8fd">
<br/>
<img width="442" alt="Skjermbilde 2023-06-26 kl  12 08 49" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/fbde29e6-5c84-40bc-9dc0-0aefc11de232">

<br/><br/>Non-anonymous session:
<img width="262" alt="Skjermbilde 2023-06-26 kl  12 15 09" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/5a0b402f-16c8-4ab8-b9c3-464d786894a1">

<img width="529" alt="Skjermbilde 2023-06-26 kl  12 15 29" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/17e3578a-3595-4870-8661-bfaad3e207f7">

**Comment by jorgenfinsveen** [comment]
> Tested with 4 different student accounts using Google Chrome and Mozilla Firefox in both with and without incognito-mode. All answers were registered and each student ID was correct.
> 
> Session report:
> 
> <img alt="Skjermbilde 2023-06-26 kl 11 50 54" width="663" src="https://user-images.githubusercontent.com/44703456/248755312-a9470934-95f7-4ae9-a7ba-e7b9c741c6dd.png">
> Attendance list:
> 
> <img alt="Skjermbilde 2023-06-26 kl 11 52 18" width="263" src="https://user-images.githubusercontent.com/44703456/248755708-fafa7def-76a8-4b3f-8757-f0fb8c8b592d.png">
> The only issue here is that the column **First Name** actually contains the users last name and vice versa. I will try to resolve this before closing the issue.

I have resolved the issue and pushed the fix to the branch named bug/#97
