### ISSUE TITLE
Test and release for Moodle 4

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#86]
When we are satisfied that #82 is resolved, we need to make a new release.
If there are any low-hanging fruits in the old issues, they may be worth fixing too.
To make the release, we use the instructions here: https://www.ntnu.no/wiki/display/iemoodle/Version+Control+and+Release+Policy  (access restricted to the team).
The new release should probably be called v2.0 because it is not backwards compatible with old versions for Moodle 3.  Opinions on this?

**Comment by julianmontague** [comment]
Blocked by #80. [hgeorgsch](https://github.com/hgeorgsch) and I were in agreement today that it is better (cleaner) to release a version for 3.X before releasing a version for 4.0
