### ISSUE TITLE
Moodle 4 - checkboxes do not work (edit quiz)

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#91]
In the right hand pane, where questions are selected, there are three checkboxes.  Unchecking them, they are immediately reset to checked.

**Comment by hgeorgsch** [comment]
This seems to be an issue with both 3.11 and 4.0

**Comment by hgeorgsch** [comment]
It looks as if the page reloads whenever a box is checked (with the exception of question selection boxes).  The choice of category persists, but the checkboxes do not.

**Comment by hgeorgsch** [comment]
Suspected problem in edit.php:66:
```
    $questionbank->display('editq', $qpage, $qperpage, $pagevars['cat'], true, true, true);
```
The three `true` parameters set the values of the checkboxes.

There are URL parameters indicating the selections, and these change, but are seemingly ignored.

**Comment by hgeorgsch** [comment]
This needs to be checked and confirm.  There is an old branch bug-91-checkboxes which was never merged.  If this is still a problem, it should be merged; otherwise this issue should be closed.

**Comment by jorgenfinsveen** [comment]
Merged develop into bug-91-checkboxes branch and tested. Problems seems to be resolved. Created new pull request
