### ISSUE TITLE
No question text in the question bank view

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#97]
Even if the checkbox is checked the question text is not shown.
We will probably have to rewrite the jazzquiz_question_bank_view based on the current implementation of core quiz.

**Comment by hgeorgsch** [comment]
This works in the core question bank; showing the question text on a separate line in the table.  To fix, one should compare our code to the question bank code.

**Comment by jorgenfinsveen** [comment]
Asked the Moodle forum for guidance regarding the implementation of a plugin specific question bank. The thread can be found <a href="https://moodle.org/mod/forum/discuss.php?d=447915">here</a>.

**Comment by jorgenfinsveen** [comment]
Have already worked a bit with this issue. I am yet to actually resolve it, but I will do as recommended in the moodle forum.

**Comment by jorgenfinsveen** [comment]
Managed to resolve this now.

Problem was that a specific column for showing the question text must be included in the columns variable in jazzquiz_question_bank_view.php. This would however make the the question text column visible regardless of the options chosen in the drop-down menu. Used the base-url to locate the qbshowtext parameter and added the question text column if its value was not equal to 0. The superclass which the jazzquiz_question_bank_view class inherits from was able to differ between the "text only" and "text and images" options by itself.


### After implementation

<br/>

**Option: No question text**

<img width="552" alt="Skjermbilde 2023-07-28 kl  14 31 06" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/a6cfcd01-a644-4050-8ea7-f3784e4e2052">

<br/><br/>

**Option: Only text**

<img width="526" alt="Skjermbilde 2023-07-28 kl  14 33 52" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/8481fd2f-2d7d-48d2-8cbd-47b4e3f40c4f">

<br/><br/>

**Option: Text and media**

<img width="534" alt="Skjermbilde 2023-07-28 kl  14 34 39" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/c68bd82b-c278-433f-9013-07eb3861b7bd">

**Comment by jorgenfinsveen** [comment]
Tested for Moodle version 4.1 using both Safari and Google Chrome
